### ISSUE TITLE
No longer required: handled by WordPress Core

### ISSUE THREAD

**Issue by markhowellsmead** [m-e-h/postcss-editor-styles#4]
Note that the use of `add_editor_style` in PHP automatically does the conversion in this code. See https://developer.wordpress.org/reference/functions/add_editor_style/#comment-5332 for further details.

**Comment by strarsis** [comment]
Also, without the iframe isolation feature, the frontend styles can be added as editor styles, which will be automatically post-processed by Gutenberg editor itself.

**Comment by markhowellsmead** [comment]
Update on this. The current version of your tech seems to have problems with nested selectors like `body foo {…}` or `body::after {…}`. These result in the generated CSS containing the rules `.editor-styles-wrapper body foo {…}` and `.editor-styles-wrapper body::after {…}`. Are you aware of this issue?

HOWEVER: as long as all blocks in the WordPress installation are compatible with version 3 of the Blocks API, the WordPress Block Editor will now be loaded in an iframe. Although this iframe still has the class name `editor-styles-wrapper`, styles enqueued using the `enqueue_block_editor_assets` hook can use the plain rule body {…} directly. This may well make the `.editor-styles-wrapper` conversion redundant for newer development.

https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/

**Comment by m-e-h** [comment]
Thanks for the update! I wasn't aware of the iframe isolation feature or v3 of the API. Sounds great! :tada: 
I know this package hasn't been updated in a while. I do still hope to find time to fix a couple of the issues at some point.
